return {
  ["tiles"] = {
    ["0_2"] = {
      ["roomType"] = "dinnersLeft",
      ["blocked"] = false,
      ["myPath"] = {
      },
      ["z"] = 2,
      ["x"] = 0,
      ["alreadyVisited"] = false,
    },
    ["0_3"] = {
      ["north"] = "0_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "0_3",
      },
      ["z"] = 3,
      ["west"] = "-1_3",
      ["x"] = 0,
      ["east"] = "1_3",
      ["alreadyVisited"] = true,
    },
    ["0_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "-1_4",
        [9] = "0_4",
      },
      ["z"] = 4,
      ["west"] = "-1_4",
      ["south"] = "0_3",
      ["x"] = 0,
      ["east"] = "1_4",
      ["alreadyVisited"] = true,
    },
    ["1_-4"] = {
      ["north"] = "1_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "1_-4",
      },
      ["z"] = -4,
      ["west"] = "0_-4",
      ["x"] = 1,
      ["east"] = "2_-4",
      ["alreadyVisited"] = true,
    },
    ["1_-3"] = {
      ["north"] = "1_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
      },
      ["z"] = -3,
      ["west"] = "0_-3",
      ["south"] = "1_-4",
      ["x"] = 1,
      ["east"] = "2_-3",
      ["alreadyVisited"] = true,
    },
    ["1_-2"] = {
      ["north"] = "1_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
      },
      ["z"] = -2,
      ["south"] = "1_-3",
      ["x"] = 1,
      ["alreadyVisited"] = true,
    },
    ["1_-1"] = {
      ["north"] = "1_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
      },
      ["z"] = -1,
      ["west"] = "0_-1",
      ["south"] = "1_-2",
      ["x"] = 1,
      ["east"] = "2_-1",
      ["alreadyVisited"] = true,
    },
    ["1_0"] = {
      ["north"] = "1_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
      },
      ["z"] = 0,
      ["west"] = "0_0",
      ["south"] = "1_-1",
      ["x"] = 1,
      ["alreadyVisited"] = true,
    },
    ["1_1"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
      },
      ["z"] = 1,
      ["west"] = "0_1",
      ["south"] = "1_0",
      ["x"] = 1,
      ["east"] = "2_1",
      ["alreadyVisited"] = true,
    },
    ["1_2"] = {
      ["roomType"] = "dinnersRight",
      ["blocked"] = false,
      ["myPath"] = {
      },
      ["z"] = 2,
      ["x"] = 1,
      ["alreadyVisited"] = false,
    },
    ["1_3"] = {
      ["north"] = "1_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "0_3",
        [9] = "1_3",
      },
      ["z"] = 3,
      ["west"] = "0_3",
      ["x"] = 1,
      ["east"] = "2_3",
      ["alreadyVisited"] = true,
    },
    ["1_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "-1_4",
        [9] = "0_4",
        [10] = "1_4",
      },
      ["z"] = 4,
      ["west"] = "0_4",
      ["south"] = "1_3",
      ["x"] = 1,
      ["east"] = "2_4",
      ["alreadyVisited"] = true,
    },
    ["2_-4"] = {
      ["north"] = "2_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "2_-4",
      },
      ["z"] = -4,
      ["west"] = "1_-4",
      ["x"] = 2,
      ["east"] = "3_-4",
      ["alreadyVisited"] = true,
    },
    ["2_-3"] = {
      ["north"] = "2_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
      },
      ["z"] = -3,
      ["west"] = "1_-3",
      ["south"] = "2_-4",
      ["x"] = 2,
      ["east"] = "3_-3",
      ["alreadyVisited"] = true,
    },
    ["2_-2"] = {
      ["roomType"] = "restroomMale",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "2_-2",
      },
      ["z"] = -2,
      ["south"] = "2_-3",
      ["x"] = 2,
      ["alreadyVisited"] = true,
    },
    ["2_-1"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
      },
      ["z"] = -1,
      ["west"] = "1_-1",
      ["x"] = 2,
      ["east"] = "3_-1",
      ["alreadyVisited"] = true,
    },
    ["2_0"] = {
      ["north"] = "2_1",
      ["roomType"] = "officeRoom",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "2_0",
      },
      ["z"] = 0,
      ["x"] = 2,
      ["alreadyVisited"] = true,
    },
    ["2_1"] = {
      ["north"] = "2_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
      },
      ["z"] = 1,
      ["west"] = "1_1",
      ["south"] = "2_0",
      ["x"] = 2,
      ["east"] = "3_1",
      ["alreadyVisited"] = true,
    },
    ["2_2"] = {
      ["roomType"] = "restroomFemale",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "2_2",
      },
      ["z"] = 2,
      ["south"] = "2_1",
      ["x"] = 2,
      ["alreadyVisited"] = true,
    },
    ["2_3"] = {
      ["north"] = "2_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "3_2",
        [7] = "3_3",
        [8] = "2_3",
      },
      ["z"] = 3,
      ["west"] = "1_3",
      ["x"] = 2,
      ["east"] = "3_3",
      ["alreadyVisited"] = true,
    },
    ["2_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "3_2",
        [7] = "3_3",
        [8] = "2_3",
        [9] = "2_4",
      },
      ["z"] = 4,
      ["west"] = "1_4",
      ["south"] = "2_3",
      ["x"] = 2,
      ["east"] = "3_4",
      ["alreadyVisited"] = true,
    },
    ["3_-4"] = {
      ["north"] = "3_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "2_-4",
        [8] = "3_-4",
      },
      ["z"] = -4,
      ["west"] = "2_-4",
      ["x"] = 3,
      ["east"] = "4_-4",
      ["alreadyVisited"] = true,
    },
    ["3_-3"] = {
      ["north"] = "3_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "3_-3",
      },
      ["z"] = -3,
      ["west"] = "2_-3",
      ["south"] = "3_-4",
      ["x"] = 3,
      ["east"] = "4_-3",
      ["alreadyVisited"] = true,
    },
    ["3_-2"] = {
      ["north"] = "3_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
        [6] = "3_-2",
      },
      ["z"] = -2,
      ["south"] = "3_-3",
      ["x"] = 3,
      ["east"] = "4_-2",
      ["alreadyVisited"] = true,
    },
    ["3_-1"] = {
      ["north"] = "3_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
      },
      ["z"] = -1,
      ["west"] = "2_-1",
      ["south"] = "3_-2",
      ["x"] = 3,
      ["east"] = "4_-1",
      ["alreadyVisited"] = true,
    },
    ["3_0"] = {
      ["north"] = "3_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
        [6] = "3_0",
      },
      ["z"] = 0,
      ["south"] = "3_-1",
      ["x"] = 3,
      ["east"] = "4_0",
      ["alreadyVisited"] = true,
    },
    ["3_1"] = {
      ["north"] = "3_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
      },
      ["z"] = 1,
      ["west"] = "2_1",
      ["south"] = "3_0",
      ["x"] = 3,
      ["east"] = "4_1",
      ["alreadyVisited"] = true,
    },
    ["3_2"] = {
      ["north"] = "3_3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "3_2",
      },
      ["z"] = 2,
      ["south"] = "3_1",
      ["x"] = 3,
      ["east"] = "4_2",
      ["alreadyVisited"] = true,
    },
    ["-4_-4"] = {
      ["north"] = "-4_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
        [7] = "-2_-4",
        [8] = "-3_-4",
        [9] = "-4_-4",
      },
      ["z"] = -4,
      ["x"] = -4,
      ["east"] = "-3_-4",
      ["alreadyVisited"] = true,
    },
    ["-4_-3"] = {
      ["north"] = "-4_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
        [7] = "-3_-3",
        [8] = "-4_-3",
      },
      ["z"] = -3,
      ["south"] = "-4_-4",
      ["x"] = -4,
      ["east"] = "-3_-3",
      ["alreadyVisited"] = true,
    },
    ["-3_-4"] = {
      ["north"] = "-3_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
        [7] = "-2_-4",
        [8] = "-3_-4",
      },
      ["z"] = -4,
      ["west"] = "-4_-4",
      ["x"] = -3,
      ["east"] = "-2_-4",
      ["alreadyVisited"] = true,
    },
    ["-4_-2"] = {
      ["north"] = "-4_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-3_-1",
        [6] = "-3_-2",
        [7] = "-4_-2",
      },
      ["z"] = -2,
      ["south"] = "-4_-3",
      ["x"] = -4,
      ["east"] = "-3_-2",
      ["alreadyVisited"] = true,
    },
    ["-3_-3"] = {
      ["north"] = "-3_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
        [7] = "-3_-3",
      },
      ["z"] = -3,
      ["west"] = "-4_-3",
      ["south"] = "-3_-4",
      ["x"] = -3,
      ["east"] = "-2_-3",
      ["alreadyVisited"] = true,
    },
    ["4_-2"] = {
      ["north"] = "4_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
        [6] = "3_-2",
        [7] = "4_-2",
      },
      ["z"] = -2,
      ["west"] = "3_-2",
      ["south"] = "4_-3",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_-1"] = {
      ["north"] = "4_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
        [6] = "4_-1",
      },
      ["z"] = -1,
      ["west"] = "3_-1",
      ["south"] = "4_-2",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_0"] = {
      ["north"] = "4_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "2_-1",
        [5] = "3_-1",
        [6] = "3_0",
        [7] = "4_0",
      },
      ["z"] = 0,
      ["west"] = "3_0",
      ["south"] = "4_-1",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_1"] = {
      ["north"] = "4_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "4_1",
      },
      ["z"] = 1,
      ["west"] = "3_1",
      ["south"] = "4_0",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_2"] = {
      ["north"] = "4_3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "4_1",
        [7] = "4_2",
      },
      ["z"] = 2,
      ["west"] = "3_2",
      ["south"] = "4_1",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_3"] = {
      ["north"] = "4_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "4_1",
        [7] = "4_2",
        [8] = "4_3",
      },
      ["z"] = 3,
      ["west"] = "3_3",
      ["south"] = "4_2",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "4_1",
        [7] = "4_2",
        [8] = "4_3",
        [9] = "4_4",
      },
      ["z"] = 4,
      ["west"] = "3_4",
      ["south"] = "4_3",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_-3"] = {
      ["north"] = "4_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "3_-3",
        [8] = "4_-3",
      },
      ["z"] = -3,
      ["west"] = "3_-3",
      ["south"] = "4_-4",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["4_-4"] = {
      ["north"] = "4_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "2_-3",
        [7] = "2_-4",
        [8] = "3_-4",
        [9] = "4_-4",
      },
      ["z"] = -4,
      ["west"] = "3_-4",
      ["x"] = 4,
      ["alreadyVisited"] = true,
    },
    ["3_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "3_2",
        [7] = "3_3",
        [8] = "3_4",
      },
      ["z"] = 4,
      ["west"] = "2_4",
      ["south"] = "3_3",
      ["x"] = 3,
      ["east"] = "4_4",
      ["alreadyVisited"] = true,
    },
    ["3_3"] = {
      ["north"] = "3_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "2_1",
        [5] = "3_1",
        [6] = "3_2",
        [7] = "3_3",
      },
      ["z"] = 3,
      ["west"] = "2_3",
      ["south"] = "3_2",
      ["x"] = 3,
      ["east"] = "4_3",
      ["alreadyVisited"] = true,
    },
    ["-4_-1"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-3_-1",
        [6] = "-4_-1",
      },
      ["z"] = -1,
      ["south"] = "-4_-2",
      ["x"] = -4,
      ["east"] = "-3_-1",
      ["alreadyVisited"] = true,
    },
    ["-3_-2"] = {
      ["north"] = "-3_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-3_-1",
        [6] = "-3_-2",
      },
      ["z"] = -2,
      ["west"] = "-4_-2",
      ["south"] = "-3_-3",
      ["x"] = -3,
      ["alreadyVisited"] = true,
    },
    ["-4_0"] = {
      ["roomType"] = "exitRoom",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-2_0",
        [6] = "-3_0",
        [7] = "-4_0",
      },
      ["z"] = 0,
      ["x"] = -4,
      ["east"] = "-3_0",
      ["alreadyVisited"] = true,
    },
    ["-3_-1"] = {
      ["north"] = "-3_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-3_-1",
      },
      ["z"] = -1,
      ["west"] = "-4_-1",
      ["south"] = "-3_-2",
      ["x"] = -3,
      ["east"] = "-2_-1",
      ["alreadyVisited"] = true,
    },
    ["-4_1"] = {
      ["north"] = "-4_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-4_1",
      },
      ["z"] = 1,
      ["x"] = -4,
      ["east"] = "-3_1",
      ["alreadyVisited"] = true,
    },
    ["-3_0"] = {
      ["north"] = "-3_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-2_0",
        [6] = "-3_0",
      },
      ["z"] = 0,
      ["west"] = "-4_0",
      ["south"] = "-3_-1",
      ["x"] = -3,
      ["east"] = "-2_0",
      ["alreadyVisited"] = true,
    },
    ["-4_2"] = {
      ["north"] = "-4_3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
        [9] = "-4_2",
      },
      ["z"] = 2,
      ["south"] = "-4_1",
      ["x"] = -4,
      ["east"] = "-3_2",
      ["alreadyVisited"] = true,
    },
    ["-3_1"] = {
      ["north"] = "-3_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
      },
      ["z"] = 1,
      ["west"] = "-4_1",
      ["south"] = "-3_0",
      ["x"] = -3,
      ["east"] = "-2_1",
      ["alreadyVisited"] = true,
    },
    ["-4_3"] = {
      ["north"] = "-4_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
        [9] = "-3_3",
        [10] = "-4_3",
      },
      ["z"] = 3,
      ["south"] = "-4_2",
      ["x"] = -4,
      ["east"] = "-3_3",
      ["alreadyVisited"] = true,
    },
    ["-3_2"] = {
      ["north"] = "-3_3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
      },
      ["z"] = 2,
      ["west"] = "-4_2",
      ["south"] = "-3_1",
      ["x"] = -3,
      ["alreadyVisited"] = true,
    },
    ["-4_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
        [9] = "-3_3",
        [10] = "-4_3",
        [11] = "-4_4",
      },
      ["z"] = 4,
      ["south"] = "-4_3",
      ["x"] = -4,
      ["east"] = "-3_4",
      ["alreadyVisited"] = true,
    },
    ["-3_3"] = {
      ["north"] = "-3_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
        [9] = "-3_3",
      },
      ["z"] = 3,
      ["west"] = "-4_3",
      ["south"] = "-3_2",
      ["x"] = -3,
      ["east"] = "-2_3",
      ["alreadyVisited"] = true,
    },
    ["-3_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
        [7] = "-3_1",
        [8] = "-3_2",
        [9] = "-3_3",
        [10] = "-3_4",
      },
      ["z"] = 4,
      ["west"] = "-4_4",
      ["south"] = "-3_3",
      ["x"] = -3,
      ["east"] = "-2_4",
      ["alreadyVisited"] = true,
    },
    ["-2_-4"] = {
      ["north"] = "-2_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
        [7] = "-2_-4",
      },
      ["z"] = -4,
      ["west"] = "-3_-4",
      ["x"] = -2,
      ["east"] = "-1_-4",
      ["alreadyVisited"] = true,
    },
    ["-2_-3"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-2_-3",
      },
      ["z"] = -3,
      ["west"] = "-3_-3",
      ["south"] = "-2_-4",
      ["x"] = -2,
      ["east"] = "-1_-3",
      ["alreadyVisited"] = true,
    },
    ["-2_-2"] = {
      ["roomType"] = "blocked3",
      ["blocked"] = false,
      ["myPath"] = {
      },
      ["z"] = -2,
      ["x"] = -2,
      ["alreadyVisited"] = false,
    },
    ["-2_-1"] = {
      ["north"] = "-2_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
      },
      ["z"] = -1,
      ["west"] = "-3_-1",
      ["x"] = -2,
      ["east"] = "-1_-1",
      ["alreadyVisited"] = true,
    },
    ["-2_0"] = {
      ["north"] = "-2_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-2_-1",
        [5] = "-2_0",
      },
      ["z"] = 0,
      ["west"] = "-3_0",
      ["south"] = "-2_-1",
      ["x"] = -2,
      ["east"] = "-1_0",
      ["alreadyVisited"] = true,
    },
    ["-2_1"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-2_1",
      },
      ["z"] = 1,
      ["west"] = "-3_1",
      ["south"] = "-2_0",
      ["x"] = -2,
      ["east"] = "-1_1",
      ["alreadyVisited"] = true,
    },
    ["-2_2"] = {
      ["roomType"] = "blocked2",
      ["blocked"] = false,
      ["myPath"] = {
      },
      ["z"] = 2,
      ["x"] = -2,
      ["alreadyVisited"] = false,
    },
    ["-2_3"] = {
      ["north"] = "-2_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "-2_3",
      },
      ["z"] = 3,
      ["west"] = "-3_3",
      ["x"] = -2,
      ["east"] = "-1_3",
      ["alreadyVisited"] = true,
    },
    ["-2_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "-1_4",
        [9] = "-2_4",
      },
      ["z"] = 4,
      ["west"] = "-3_4",
      ["south"] = "-2_3",
      ["x"] = -2,
      ["east"] = "-1_4",
      ["alreadyVisited"] = true,
    },
    ["-1_-4"] = {
      ["north"] = "-1_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
        [6] = "-1_-4",
      },
      ["z"] = -4,
      ["west"] = "-2_-4",
      ["x"] = -1,
      ["east"] = "0_-4",
      ["alreadyVisited"] = true,
    },
    ["-1_-3"] = {
      ["north"] = "-1_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "-1_-3",
      },
      ["z"] = -3,
      ["west"] = "-2_-3",
      ["south"] = "-1_-4",
      ["x"] = -1,
      ["east"] = "0_-3",
      ["alreadyVisited"] = true,
    },
    ["-1_-2"] = {
      ["north"] = "-1_-1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
      },
      ["z"] = -2,
      ["south"] = "-1_-3",
      ["x"] = -1,
      ["east"] = "0_-2",
      ["alreadyVisited"] = true,
    },
    ["-1_-1"] = {
      ["north"] = "-1_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
      },
      ["z"] = -1,
      ["west"] = "-2_-1",
      ["south"] = "-1_-2",
      ["x"] = -1,
      ["east"] = "0_-1",
      ["alreadyVisited"] = true,
    },
    ["-1_0"] = {
      ["north"] = "-1_1",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_0",
      },
      ["z"] = 0,
      ["west"] = "-2_0",
      ["south"] = "-1_-1",
      ["x"] = -1,
      ["alreadyVisited"] = true,
    },
    ["-1_1"] = {
      ["north"] = "-1_2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
      },
      ["z"] = 1,
      ["west"] = "-2_1",
      ["south"] = "-1_0",
      ["x"] = -1,
      ["east"] = "0_1",
      ["alreadyVisited"] = true,
    },
    ["-1_2"] = {
      ["north"] = "-1_3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
      },
      ["z"] = 2,
      ["south"] = "-1_1",
      ["x"] = -1,
      ["alreadyVisited"] = true,
    },
    ["-1_3"] = {
      ["north"] = "-1_4",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
      },
      ["z"] = 3,
      ["west"] = "-2_3",
      ["south"] = "-1_2",
      ["x"] = -1,
      ["east"] = "0_3",
      ["alreadyVisited"] = true,
    },
    ["-1_4"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
        [5] = "-1_1",
        [6] = "-1_2",
        [7] = "-1_3",
        [8] = "-1_4",
      },
      ["z"] = 4,
      ["west"] = "-2_4",
      ["south"] = "-1_3",
      ["x"] = -1,
      ["east"] = "0_4",
      ["alreadyVisited"] = true,
    },
    ["0_-4"] = {
      ["north"] = "0_-3",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "0_-3",
        [7] = "0_-4",
      },
      ["z"] = -4,
      ["west"] = "-1_-4",
      ["x"] = 0,
      ["east"] = "1_-4",
      ["alreadyVisited"] = true,
    },
    ["0_-3"] = {
      ["north"] = "0_-2",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_-1",
        [4] = "1_-2",
        [5] = "1_-3",
        [6] = "0_-3",
      },
      ["z"] = -3,
      ["west"] = "-1_-3",
      ["south"] = "0_-4",
      ["x"] = 0,
      ["east"] = "1_-3",
      ["alreadyVisited"] = true,
    },
    ["0_-2"] = {
      ["roomType"] = "kitchen",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
        [3] = "-1_-1",
        [4] = "-1_-2",
        [5] = "0_-2",
      },
      ["z"] = -2,
      ["west"] = "-1_-2",
      ["south"] = "0_-3",
      ["x"] = 0,
      ["alreadyVisited"] = true,
    },
    ["0_-1"] = {
      ["north"] = "0_0",
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "0_-1",
      },
      ["z"] = -1,
      ["west"] = "-1_-1",
      ["x"] = 0,
      ["east"] = "1_-1",
      ["alreadyVisited"] = true,
    },
    ["0_0"] = {
      ["roomType"] = "ritualRoom",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
      },
      ["z"] = 0,
      ["south"] = "0_-1",
      ["x"] = 0,
      ["east"] = "1_0",
      ["alreadyVisited"] = true,
    },
    ["0_1"] = {
      ["roomType"] = "undefined",
      ["blocked"] = false,
      ["myPath"] = {
        [1] = "0_0",
        [2] = "1_0",
        [3] = "1_1",
        [4] = "0_1",
      },
      ["z"] = 1,
      ["west"] = "-1_1",
      ["x"] = 0,
      ["east"] = "1_1",
      ["alreadyVisited"] = true,
    },
  },
  ["minX"] = -4,
  ["maxX"] = 4,
  ["minZ"] = -4,
  ["maxZ"] = 4,
}